### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by PowerhouseFR** [cdigruttola/paypaltracking#1]
Hello,
First of all, thanks for the amazing work that your plugin is solving.
I tried to compile but I got an error.
After examinating, I saw that some file you are calling in your "cp" command lines are missing from the archive available in github.

cp: cannot stat 'docs': No such file or directory
cp: cannot stat 'override': No such file or directory
cp: cannot stat 'logo.png': No such file or directory

Can you please update this? 

Many thanks,

**Comment by cdigruttola** [comment]
Hello,
I update the file to compile.
