### ISSUE TITLE
Can't open module configuration

### ISSUE THREAD

**Issue by szildaniel** [cdigruttola/paypaltracking#2]
Hi,

I am trying to run your module on my Prestashop, but it seems that it have some bugs. Firstly I had an error:
`1/1) FatalThrowableError Parse error: syntax error, unexpected 'int' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in AddPayPalCarrierTrackingCommand.php line 35` 

So I switched to php 7.4 and error is gone, but I think you need to update module requirments to 7.4 or higher, because of type declaration: `private int $carrierId;`.

Then I face an issue:
`RuntimeException
HTTP 500 Internal Server Error
Service "cdigruttola.module.paypaltracking.bundle.form.admin.paypal_carrier_tracking": Parent definition "form.type.translatable.aware" does not exist.`

Do you have any suggestion how to fix that?

PS Version: 1.7.1.1
PHP: 7.4.33
Server: Linux #1 SMP Debian 4.19.269-1 (2022-12-20) x86_64
Server software: Apache
Wersja oprogramowania serwera: Apache
MySQL: 10.3.39-MariaDB-0+deb10u1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

**Comment by cdigruttola** [comment]
Hi, the problem is the prestashop version, the form.type.translatable.aware was added in 1.7.7. Sorry, I thought I info in Readme
