### ISSUE TITLE
Error when module is enabled

### ISSUE THREAD

**Issue by tom-texier** [cdigruttola/paypaltracking#3]
Hi,

The activation of the module is going well but once activated, I get an error:
```
Service "cdigruttola.module.paypaltracking.bundle.form.admin.paypal_carrier_tracking": Parent definition "form.type.translatable.aware" does not exist.

[Symfony\Component\DependencyInjection\Exception\RuntimeException 0] 
```

Do you have an idea to fix this bug?

---

PS Version: 1.7.7.8
PHP  Version : 7.4.33
Server: Linux # 1 SMP Debian 4.9.210-1 (2020-06-09) x86_64
Server Software: Apache
MySQL: 10.4.17-MariaDB-1:10.4.17

**Comment by cdigruttola** [comment]
Could you please activate the debug mode and send mi the complete stack trace? Could you also check the presence of file src\PrestaShopBundle\Form\Admin\Type\TranslatorAwareType.php?

**Comment by cdigruttola** [comment]
Hi,
I checked with Prestashop community support, it seems that in same version this code doesn't work. I'm going to try to fix it

**Comment by tom-texier** [comment]
Hi,

Here is the complete stack trace:

![screencapture-pc5s8bacbu-preview-infomaniak-website-admin818vidcwd-index-php-2023-07-24-10_09_30](https://github.com/cdigruttola/paypaltracking/assets/66750714/8fd08d90-18df-43ef-8831-b5b9fe1f8df8)

Also, the file *src\PrestaShopBundle\Form\Admin\Type\TranslatorAwareType.php* is present.

**Comment by tom-texier** [comment]
It's the same bug for:
```yml
parent: "prestashop.core.grid.definition.factory.abstract_grid_definition"
```
in /config/admin/services.yml at line 20

and 
```yml
parent: 'prestashop.core.grid.abstract_query_builder'
```
in /config/admin/services.yml at line 33

**Comment by tom-texier** [comment]
I think your module is compatible with Prestashop 1.8 at least.

**Comment by cdigruttola** [comment]
I'm using on Prestashop 1.7.8.9 and it's working.

**Comment by tom-texier** [comment]
Sorry, I meant Prestashop 1.7.8.
In your README.md you say it's compatible with version 1.7.7 or higher.
My version is 1.7.7.8 and it doesn’t work.

**Comment by cdigruttola** [comment]
Yes, I'm changing the README. I also ask to Prestashop community and it seems a known problem.
